# Container vazio.
FROM scratch

# Metadata
LABEL Vendor="Diego Rocha" \
      Description="Gestor de chamadas de usuários" \
      Version="0.1.0"

# Copiar binários
# ADD ./ /go/bin/user-invoices

# 
EXPOSE 5000:50
# ENTRYPOINT ["/bin/user-invoices"]


