version: '3.4'
services:

 db:
  restart: always
  image: postgres:alpine
  container_name: postgres
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   # Considerar local de referência do docker-compose.yml
   # $LOCALDIR/rsc/compose
   - ../../rsc/sql/:/docker-entrypoint-initdb.d/
   - pgdata:/var/lib/postgresql/data
  environment:
   - POSTGRES_DB=pgtap
   - POSTGRES_USER=pgtap
   - POSTGRES_PASSWORD=pgtap
   # - PGDATA=/var/lib/postgresql/data
   - POSTGRES_INITDB_ARGS=--data-checksums
  ports:
   - 5432:5432

 test-db:
  restart: always
  image: dhsrocha/pgtap
  container_name: postgres
  build:
   context: ../../
   dockerfile: pub/dockerfile/pgtap.Dockerfile
   args:
    - PGTAP_VER=v0.98.0
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - pgdata:/var/lib/postgresql/data
  depends_on:
   - db
  links:
   - db

volumes:
 pgdata:
  name: pgtap-data

